name: first-action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo 'Hello'
      - name : Prinf Bye
        run: echo 'Bye'
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: node Installed
        run: echo 'Node Installed'
  second-job:
    runs-on: unbuntu-latest
    steps:
      - name: Print Hello Second
        run: echo 'Hello Second'
      - name: env value
        run: echo "${{ toJSON(github) }}"
