name: first-action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo 'Hello'
      - name : Prinf Bye
        run: echo 'Bye'
      - name: Install Node
        run: actions/setup-node@v3
      - name: node Installed
        run: echo 'Node Installed'
